---
name: Automerge
on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'ci'
jobs:
  automerge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: NikitaSkrynnik/.github/.github/workflows/automerge.yaml@reusable-workflows