---
name: ci
on:
  pull_request:
  push:
    branches:
      - 'release/**'
jobs:
  yamllint:
    uses: NikitaSkrynnik/.github/.github/workflows/yamllint.yaml@reusable-workflows

  build-and-test:
    uses: NikitaSkrynnik/.github/.github/workflows/build-and-test.yaml@reusable-workflows
    with:
      os: '["ubuntu-latest", "macos-latest", "windows-latest"]'
  
  golangci-lint:
    uses: NikitaSkrynnik/.github/.github/workflows/golangci-lint.yaml@reusable-workflows
