---
name: ci
on:
  pull_request:
  push:
    branches:
      - 'release/**'
jobs:
  yamllint:
    uses: NikitaSkrynnik/.github/.github/workflows/yamllint.yaml@reusable-workflows

  golangci-lint:
    uses: NikitaSkrynnik/.github/.github/workflows/golangci-lint.yaml@reusable-workflows
